### ISSUE TITLE
Conversion error when building

### ISSUE THREAD

**Issue by PullJosh** [rw-r-r-0644/Flappy-Bird_GX2#1]
I'd love to have a play around with modifying this game, but I can't seem to build it. When I run `make`, I get this error:
```
pulljosh@PullJosh:~/Code/wiiu/Flappy-Bird_GX2$ make
main.cpp
In file included from /home/pulljosh/Code/wiiu/Flappy-Bird_GX2/src/system/AsyncDeleter.h:21:0,
                 from /home/pulljosh/Code/wiiu/Flappy-Bird_GX2/src/gui/GuiElement.h:37,
                 from /home/pulljosh/Code/wiiu/Flappy-Bird_GX2/src/gui/Gui.h:20,
                 from /home/pulljosh/Code/wiiu/Flappy-Bird_GX2/src/menu/MainWindow.h:23,
                 from /home/pulljosh/Code/wiiu/Flappy-Bird_GX2/src/Application.h:20,
                 from /home/pulljosh/Code/wiiu/Flappy-Bird_GX2/src/main.cpp:1:
/home/pulljosh/Code/wiiu/Flappy-Bird_GX2/src/system/CThread.h: In constructor 'CThread::CThread(int, int, int, CThread::Callback, void*)':
/home/pulljosh/Code/wiiu/Flappy-Bird_GX2/src/system/CThread.h:46:37: error: invalid conversion from 'int (*)(int, void*)' to 's32 (*)(s32, void*) {aka long int (*)(long int, void*)}' [-fpermissive]
             OSCreateThread(pThread, &CThread::threadCallback, 1, this, (u32)pThreadStack+iStackSize, iStackSize, iPriority, iAttributes);
                                     ^~~~~~~~
/home/pulljosh/Code/wiiu/Flappy-Bird_GX2/Makefile:175: recipe for target 'main.o' failed
make[1]: *** [main.o] Error 1
Makefile:137: recipe for target 'build' failed
make: *** [build] Error 2
```
I'm currently using Ubuntu, if that matters any. (I also have virtually no experience with C, so type casting is a bit of a foreign concept...)

**Comment by CreeperMario** [comment]
It seems that your devkitpro setup defines an int differently to that of @rw-r-r-0644's.
Theoretically, s32 and int should be the same thing, yet your implementation defines s32 as long int.
Are you using the latest version of devkitPPC? [(r28)](https://sourceforge.net/projects/devkitpro/files/devkitPPC/) If not, try it out.
If you are, try building it using [r27](https://sourceforge.net/projects/devkitpro/files/devkitPPC/).

You can find out which version you are using by navigating to your `devkitPPC/bin` folder and running the command `./powerpc-eabi-gcc -v`.

**Comment by PullJosh** [comment]
Aha! Switching to r27 did the trick. Thanks for the help!

**For (potential) future readers:** There was a bit of a strange thing happenening, where even after switching to r27, `./powerpc-eabi-gcc -v` still told me I was running r28. However, the compilation worked fine. Just a heads up. ;)
